import React from 'react';
import styled from 'styled-components';

import generateThemeItem from '../../HelperFunctions/generateThemeItem';
import { IGenerateThemeItem } from '../../HelperFunctions/generateThemeItem';
import FancySVGAtom from '../../Atoms/FancySVGAtom/FancySVGAtom';
import Typography from '../../Atoms/Typography/Typography';
import { disabledStyle } from '../../HelperFunctions/disableStyle';

// the style is generated by the generateThemeItem function
const A = styled.a<IGenerateThemeItem & {disabled?: boolean}>`
  ${(props: IGenerateThemeItem) => generateThemeItem(props)}
  ${({disabled}) => disabled ? disabledStyle : ''}

`;

// --------------------------------------------------------------------------- //
// --------------- The Main Component for the Fancy A Tag -------------------- //
// --------------------------------------------------------------------------- //
export interface IFancyA {
  size: "small" | "medium" | "large";
  wide?: boolean; 
  design: "primary" | "secondary" | "accent" | "transparent";
  align?: "left" | "right" | "center";
  color?: "primary" | "secondary" | "accent";
  hoverColor?: "primary" | "secondary" | "accent";
  label?: string;
  outlined?: boolean;
  icon?: JSX.Element;
  disabled?: boolean;
  onClick?: () => void;
}
export default function FancyA(props: IFancyA) {
  const { icon, label, outlined, size, design, align, color, wide, hoverColor, disabled, onClick  } = {...defaultProps, ...props};

  return (
    <A
      $size={size}
      $design={design}
      $align={align}
      $color={color}
      $wide={wide}
      $icon={icon}
      $hoverColor={hoverColor}
      $label={label}
      $outlined={outlined}
      disabled={disabled}
      onClick={onClick}
    >
      {icon && <FancySVGAtom size={props.size}>{icon}</FancySVGAtom>}
      {label && <Typography type='inlineElement' variant='label'>{label}</Typography>}
    </A>
  );
}

const defaultProps: IFancyA = {
  size: 'medium',
  design: 'transparent',
  align: 'left',
  hoverColor: 'accent',
  outlined: false,
  disabled: false,
};
